const Exercise_Images = {
    "Back Extension": require('./assets/Exercises_images/back/Back Extension.jpg'),
    "Barbell Shrug": require('./assets/Exercises_images/back/Barbell Shrug.jpg'),
    "Bent Over Barbell Row": require('./assets/Exercises_images/back/Bent Over Barbell Row.jpg'),
    "Bent Over Dumbbell Row": require('./assets/Exercises_images/back/Bent Over Dumbbell Row.jpg'),
    "Cable Reverse Fly": require('./assets/Exercises_images/back/Cable Reverse Fly.jpg'),
    "Cable Shrug": require('./assets/Exercises_images/back/Cable Shrug.jpg'),
    "Cable Upright Row": require('./assets/Exercises_images/back/Cable Upright Row.jpg'),
    "Chest Supported Dumbbell Row": require('./assets/Exercises_images/back/Chest Supported Dumbbell Row.jpg'),
    "Chin Ups": require('./assets/Exercises_images/back/Chin Ups.jpg'),
    "Close Grip Lat Pulldown": require('./assets/Exercises_images/back/Close Grip Lat Pulldown.jpg'),
    "Dumbbell Pullover": require('./assets/Exercises_images/back/Dumbbell Pullover.jpg'),
    "Dumbbell Reverse Fly": require('./assets/Exercises_images/back/Dumbbell Reverse Fly.jpg'),
    "Dumbbell Row": require('./assets/Exercises_images/back/Dumbbell Row.jpg'),
    "Dumbbell Shrug": require('./assets/Exercises_images/back/Dumbbell Shrug.jpg'),
    "Inverted Row": require('./assets/Exercises_images/back/Inverted Row.jpg'),
    "Lat Pulldown": require('./assets/Exercises_images/back/Lat Pulldown.jpg'),
    "Machine Back Extension": require('./assets/Exercises_images/back/Machine Back Extension.jpg'),
    "Machine Reverse Fly": require('./assets/Exercises_images/back/Machine Reverse Fly.jpg'),
    "Machine Row": require('./assets/Exercises_images/back/Machine Row.jpg'),
    "Machine Shrug": require('./assets/Exercises_images/back/Machine Shrug.jpg'),
    "Neutral Grip Pull Ups": require('./assets/Exercises_images/back/Neutral Grip Pull Ups.jpg'),
    "One Arm Lat Pulldown": require('./assets/Exercises_images/back/One Arm Lat Pulldown.jpg'),
    "One Arm Seated Cable Row": require('./assets/Exercises_images/back/One Arm Seated Cable Row.jpg'),
    "Pull Ups": require('./assets/Exercises_images/back/Pull Ups.jpg'),
    "Renegade Row": require('./assets/Exercises_images/back/Renegade Row.jpg'),
    "Reverse Grip Lat Pulldown": require('./assets/Exercises_images/back/Reverse Grip Lat Pulldown.jpg'),
    "Seated Cable Row": require('./assets/Exercises_images/back/Seated Cable Row.jpg'),
    "Straight Arm Pulldown": require('./assets/Exercises_images/back/Straight Arm Pulldown.jpg'),
    "T Bar Row": require('./assets/Exercises_images/back/T Bar Row.jpg'),

    "Barbell Curl": require('./assets/Exercises_images/biceps/Barbell Curl.jpg'),
    "Cable Bicep Curl": require('./assets/Exercises_images/biceps/Cable Bicep Curl.jpg'),
    "Cable Hammer Curl": require('./assets/Exercises_images/biceps/Cable Hammer Curl.jpg'),
    "Cheat Curl": require('./assets/Exercises_images/biceps/Cheat Curl.jpg'),
    "Dumbbell Concentration Curl": require('./assets/Exercises_images/biceps/Dumbbell Concentration Curl.jpg'),
    "Dumbbell Curl": require('./assets/Exercises_images/biceps/Dumbbell Curl.jpg'),
    "EZ Bar Curl": require('./assets/Exercises_images/biceps/EZ Bar Curl.jpg'),
    "Hammer Curl": require('./assets/Exercises_images/biceps/Hammer Curl.jpg'),
    "Incline Cable Curl": require('./assets/Exercises_images/biceps/Incline Cable Curl.jpg'),
    "Incline Dumbbell Curl": require('./assets/Exercises_images/biceps/Incline Dumbbell Curl.jpg'),
    "Incline Hammer Curl": require('./assets/Exercises_images/biceps/Incline Hammer Curl.jpg'),
    "Machine Preacher Curl": require('./assets/Exercises_images/biceps/Machine Preacher Curl.jpg'),
    "One Arm Cable Bicep Curl": require('./assets/Exercises_images/biceps/One Arm Cable Bicep Curl.jpg'),
    "One Arm Dumbbell Preacher Curl": require('./assets/Exercises_images/biceps/One Arm Dumbbell Preacher Curl.jpg'),
    "One Arm Pulldown": require('./assets/Exercises_images/biceps/One Arm Pulldown.jpg'),
    "Overhead Cable Curl": require('./assets/Exercises_images/biceps/Overhead Cable Curl.jpg'),
    "Preacher Curl": require('./assets/Exercises_images/biceps/Preacher Curl.jpg'),
    "Zottman Curl": require('./assets/Exercises_images/biceps/Zottman Curl.jpg'),

    "Archer Push Up": require('./assets/Exercises_images/chest/Archer Push Up.jpg'),
    "Bench Press": require('./assets/Exercises_images/chest/Bench Press.jpg'),
    "Cable Fly": require('./assets/Exercises_images/chest/Cable Fly.jpg'),
    "Close Grip Bench Press": require('./assets/Exercises_images/chest/Close Grip Bench Press.jpg'),
    "Close Grip Dumbbell Bench Press": require('./assets/Exercises_images/chest/Close Grip Dumbbell Bench Press.jpg'),
    "Close Grip Push Up": require('./assets/Exercises_images/chest/Close Grip Push Up.jpg'),
    "Decline Bench Press": require('./assets/Exercises_images/chest/Decline Bench Press.jpg'),
    "Decline Dumbbell Bench Press": require('./assets/Exercises_images/chest/Decline Dumbbell Bench Press.jpg'),
    "Decline Dumbbell Fly": require('./assets/Exercises_images/chest/Decline Dumbbell Fly.jpg'),
    "Decline Push Up": require('./assets/Exercises_images/chest/Decline Push Up.jpg'),
    "Diamond Push Ups": require('./assets/Exercises_images/chest/Diamond Push Ups.jpg'),
    "Dumbbell Bench Press": require('./assets/Exercises_images/chest/Dumbbell Bench Press.jpg'),
    "Dumbbell Fly": require('./assets/Exercises_images/chest/Dumbbell Fly.jpg'),
    "Incline Bench Press": require('./assets/Exercises_images/chest/Incline Bench Press.jpg'),
    "Incline Dumbbell Bench Press": require('./assets/Exercises_images/chest/Incline Dumbbell Bench Press.jpg'),
    "Incline Dumbbell Fly": require('./assets/Exercises_images/chest/Incline Dumbbell Fly.jpg'),
    "Incline Push Up": require('./assets/Exercises_images/chest/Incline Push Up.jpg'),
    "Machine Chest Fly": require('./assets/Exercises_images/chest/Machine Chest Fly.jpg'),
    "Machine Chest Press": require('./assets/Exercises_images/chest/Machine Chest Press.jpg'),
    "One Arm Push Ups": require('./assets/Exercises_images/chest/One Arm Push Ups.jpg'),
    "Push Ups": require('./assets/Exercises_images/chest/Push Ups.jpg'),
    "Reverse Grip Bench Press": require('./assets/Exercises_images/chest/Reverse Grip Bench Press.jpg'),
    "Smith Machine Bench Press": require('./assets/Exercises_images/chest/Smith Machine Bench Press.jpg'),
    "Wide Grip Bench Press": require('./assets/Exercises_images/chest/Wide Grip Bench Press.jpg'),

    "Ab Wheel Rollout": require('./assets/Exercises_images/core/Ab Wheel Rollout.jpg'),
    "Bicycle Crunch": require('./assets/Exercises_images/core/Bicycle Crunch.jpg'),
    "Cable Crunch": require('./assets/Exercises_images/core/Cable Crunch.jpg'),
    "Cable Woodchopper": require('./assets/Exercises_images/core/Cable Woodchopper.jpg'),
    "Crunches": require('./assets/Exercises_images/core/Crunches.jpg'),
    "Decline Crunch": require('./assets/Exercises_images/core/Decline Crunch.jpg'),
    "Decline Sit Up": require('./assets/Exercises_images/core/Decline Sit Up.jpg'),
    "Dumbbell Side Bend": require('./assets/Exercises_images/core/Dumbbell Side Bend.jpg'),
    "Flutter Kicks": require('./assets/Exercises_images/core/Flutter Kicks.jpg'),
    "Hanging Knee Raise": require('./assets/Exercises_images/core/Hanging Knee Raise.jpg'),
    "Hanging Leg Raise": require('./assets/Exercises_images/core/Hanging Leg Raise.jpg'),
    "High Pulley Crunch": require('./assets/Exercises_images/core/High Pulley Crunch.jpg'),
    "Jumping Jack": require('./assets/Exercises_images/core/Jumping Jack.jpg'),
    "Lying Leg Raise": require('./assets/Exercises_images/core/Lying Leg Raise.jpg'),
    "Machine Seated Crunch": require('./assets/Exercises_images/core/Machine Seated Crunch.jpg'),
    "Mountain Climbers": require('./assets/Exercises_images/core/Mountain Climbers.jpg'),
    "Reverse Crunches": require('./assets/Exercises_images/core/Reverse Crunches.jpg'),
    "Roman Chair Side Bend": require('./assets/Exercises_images/core/Roman Chair Side Bend.jpg'),
    "Russian Twist": require('./assets/Exercises_images/core/Russian Twist.jpg'),
    "Scissor Kicks": require('./assets/Exercises_images/core/Scissor Kicks.jpg'),
    "Side Crunch": require('./assets/Exercises_images/core/Side Crunch.jpg'),
    "Sit Ups": require('./assets/Exercises_images/core/Sit Ups.jpg'),
    "Superman": require('./assets/Exercises_images/core/Superman.jpg'),
    "Toes To Bar": require('./assets/Exercises_images/core/Toes To Bar.jpg'),

    "Dumbbell Reverse Curl": require('./assets/Exercises_images/forearms/Dumbbell Reverse Curl.jpg'),
    "Dumbbell Reverse Wrist Curl": require('./assets/Exercises_images/forearms/Dumbbell Reverse Wrist Curl.jpg'),
    "Dumbbell Wrist Curl": require('./assets/Exercises_images/forearms/Dumbbell Wrist Curl.jpg'),
    "Reverse Barbell Curl": require('./assets/Exercises_images/forearms/Reverse Barbell Curl.jpg'),
    "Reverse Wrist Curl": require('./assets/Exercises_images/forearms/Reverse Wrist Curl.jpg'),
    "Wrist Curl": require('./assets/Exercises_images/forearms/Wrist Curl.jpg'),

    "Barbell Calf Raise": require('./assets/Exercises_images/legs/Barbell Calf Raise.jpg'),
    "Barbell Glute Bridge": require('./assets/Exercises_images/legs/Barbell Glute Bridge.jpg'),
    "Barbell Hack Squat": require('./assets/Exercises_images/legs/Barbell Hack Squat.jpg'),
    "Barbell Lunge": require('./assets/Exercises_images/legs/Barbell Lunge.jpg'),
    "Barbell Reverse Lunge": require('./assets/Exercises_images/legs/Barbell Reverse Lunge.jpg'),
    "Bodyweight Calf Raise": require('./assets/Exercises_images/legs/Bodyweight Calf Raise.jpg'),
    "Bodyweight Squat": require('./assets/Exercises_images/legs/Bodyweight Squat.jpg'),
    "Bulgarian Split Squat": require('./assets/Exercises_images/legs/Bulgarian Split Squat.jpg'),
    "Cable Kickback": require('./assets/Exercises_images/legs/Cable Kickback.jpg'),
    "Cable Leg Extension": require('./assets/Exercises_images/legs/Cable Leg Extension.jpg'),
    "Cable Pull Through": require('./assets/Exercises_images/legs/Cable Pull Through.jpg'),
    "Dumbbell Bulgarian Split Squat": require('./assets/Exercises_images/legs/Dumbbell Bulgarian Split Squat.jpg'),
    "Dumbbell Calf Raise": require('./assets/Exercises_images/legs/Dumbbell Calf Raise.jpg'),
    "Dumbbell Front Squat": require('./assets/Exercises_images/legs/Dumbbell Front Squat.jpg'),
    "Dumbbell Lunge": require('./assets/Exercises_images/legs/Dumbbell Lunge.jpg'),
    "Dumbbell Split Squat": require('./assets/Exercises_images/legs/Dumbbell Split Squat.jpg'),
    "Dumbbell Squat": require('./assets/Exercises_images/legs/Dumbbell Squat.jpg'),
    "Floor Hip Abduction": require('./assets/Exercises_images/legs/Floor Hip Abduction.jpg'),
    "Floor Hip Extension": require('./assets/Exercises_images/legs/Floor Hip Extension.jpg'),
    "Front Squat": require('./assets/Exercises_images/legs/Front Squat.jpg'),
    "Glute Bridge": require('./assets/Exercises_images/legs/Glute Bridge.jpg'),
    "Glute Kickback": require('./assets/Exercises_images/legs/Glute Kickback.jpg'),
    "Goblet Squat": require('./assets/Exercises_images/legs/Goblet Squat.jpg'),
    "Hack Squat": require('./assets/Exercises_images/legs/Hack Squat.jpg'),
    "Hip Abduction": require('./assets/Exercises_images/legs/Hip Abduction.jpg'),
    "Hip Adduction": require('./assets/Exercises_images/legs/Hip Adduction.jpg'),
    "Hip Extension": require('./assets/Exercises_images/legs/Hip Extension.jpg'),
    "Hip Thrust": require('./assets/Exercises_images/legs/Hip Thrust.jpg'),
    "Landmine Squat": require('./assets/Exercises_images/legs/Landmine Squat.jpg'),
    "Leg Extension": require('./assets/Exercises_images/legs/Leg Extension.jpg'),
    "Leg Press": require('./assets/Exercises_images/legs/Leg Press.jpg'),
    "Lunge": require('./assets/Exercises_images/legs/Lunge.jpg'),
    "Lying Leg Curl": require('./assets/Exercises_images/legs/Lying Leg Curl.jpg'),
    "Machine Calf Raise": require('./assets/Exercises_images/legs/Machine Calf Raise.jpg'),
    "Overhead Squat": require('./assets/Exercises_images/legs/Overhead Squat.jpg'),
    "Pistol Squat": require('./assets/Exercises_images/legs/Pistol Squat.jpg'),
    "Reverse Lunge": require('./assets/Exercises_images/legs/Reverse Lunge.jpg'),
    "Seated Calf Raise": require('./assets/Exercises_images/legs/Seated Calf Raise.jpg'),
    "Seated Leg Curl": require('./assets/Exercises_images/legs/Seated Leg Curl.jpg'),
    "Side Leg Raise": require('./assets/Exercises_images/legs/Side Leg Raise.jpg'),
    "Side Lunge": require('./assets/Exercises_images/legs/Side Lunge.jpg'),
    "Single Leg Press": require('./assets/Exercises_images/legs/Single Leg Press.jpg'),
    "Single Leg Seated Calf Raise": require('./assets/Exercises_images/legs/Single Leg Seated Calf Raise.jpg'),
    "Single Leg Squat": require('./assets/Exercises_images/legs/Single Leg Squat.jpg'),
    "Smith Machine Squat": require('./assets/Exercises_images/legs/Smith Machine Squat.jpg'),
    "Split Squat": require('./assets/Exercises_images/legs/Split Squat.jpg'),
    "Squat Jump": require('./assets/Exercises_images/legs/Squat Jump.jpg'),
    "Squat": require('./assets/Exercises_images/legs/Squat.jpg'),
    "Sumo Squat": require('./assets/Exercises_images/legs/Sumo Squat.jpg'),
    "Vertical Leg Press": require('./assets/Exercises_images/legs/Vertical Leg Press.jpg'),
    "Walking Lunge": require('./assets/Exercises_images/legs/Walking Lunge.jpg'),

    "Arnold Press": require('./assets/Exercises_images/shoulders/Arnold Press.jpg'),
    "Barbell Front Raise": require('./assets/Exercises_images/shoulders/Barbell Front Raise.jpg'),
    "Behind The Neck Press": require('./assets/Exercises_images/shoulders/Behind The Neck Press.jpg'),
    "Cable External Rotation": require('./assets/Exercises_images/shoulders/Cable External Rotation.jpg'),
    "Cable Face Pull": require('./assets/Exercises_images/shoulders/Cable Face Pull.jpg'),
    "Cable Lateral Raise": require('./assets/Exercises_images/shoulders/Cable Lateral Raise.jpg'),
    "Dumbbell External Rotation": require('./assets/Exercises_images/shoulders/Dumbbell External Rotation.jpg'),
    "Dumbbell Face Pull": require('./assets/Exercises_images/shoulders/Dumbbell Face Pull.jpg'),
    "Dumbbell Front Raise": require('./assets/Exercises_images/shoulders/Dumbbell Front Raise.jpg'),
    "Dumbbell Lateral Raise": require('./assets/Exercises_images/shoulders/Dumbbell Lateral Raise.jpg'),
    "Dumbbell Push Press": require('./assets/Exercises_images/shoulders/Dumbbell Push Press.jpg'),
    "Dumbbell Shoulder Press": require('./assets/Exercises_images/shoulders/Dumbbell Shoulder Press.jpg'),
    "Dumbbell Upright Row": require('./assets/Exercises_images/shoulders/Dumbbell Upright Row.jpg'),
    "Handstand Push Ups": require('./assets/Exercises_images/shoulders/Handstand Push Ups.jpg'),
    "Landmine Press": require('./assets/Exercises_images/shoulders/Landmine Press.jpg'),
    "Machine Lateral Raise": require('./assets/Exercises_images/shoulders/Machine Lateral Raise.jpg'),
    "Machine Shoulder Press": require('./assets/Exercises_images/shoulders/Machine Shoulder Press.jpg'),
    "Military Press": require('./assets/Exercises_images/shoulders/Military Press.jpg'),
    "One Arm Landmine Press": require('./assets/Exercises_images/shoulders/One Arm Landmine Press.jpg'),
    "Pike Push Up": require('./assets/Exercises_images/shoulders/Pike Push Up.jpg'),
    "Shoulder Press": require('./assets/Exercises_images/shoulders/Shoulder Press.jpg'),
    "Upright Row": require('./assets/Exercises_images/shoulders/Upright Row.jpg'),



    "Barbell Skull Crushers": require('./assets/Exercises_images/triceps/Barbell Skull Crushers.jpg'),
    "Bench Dips": require('./assets/Exercises_images/triceps/Bench Dips.jpg'),
    "Cable Overhead Tricep Extension": require('./assets/Exercises_images/triceps/Cable Overhead Tricep Extension.jpg'),
    "Dips": require('./assets/Exercises_images/triceps/Dips.jpg'),
    "Dumbbell Skull Crushers": require('./assets/Exercises_images/triceps/Dumbbell Skull Crushers.jpg'),
    "Dumbbell Tricep Extension": require('./assets/Exercises_images/triceps/Dumbbell Tricep Extension.jpg'),
    "Dumbbell Tricep Kickback": require('./assets/Exercises_images/triceps/Dumbbell Tricep Kickback.jpg'),
    "JM Press": require('./assets/Exercises_images/triceps/JM Press.jpg'),
    "Machine Tricep Extension": require('./assets/Exercises_images/triceps/Machine Tricep Extension.jpg'),
    "Reverse Grip Tricep Pushdown": require('./assets/Exercises_images/triceps/Reverse Grip Tricep Pushdown.jpg'),
    "Ring Dips": require('./assets/Exercises_images/triceps/Ring Dips.jpg'),
    "Tate Press": require('./assets/Exercises_images/triceps/Tate Press.jpg'),
    "Tricep Pushdown": require('./assets/Exercises_images/triceps/Tricep Pushdown.jpg'),
    "Tricep Rope Pushdown": require('./assets/Exercises_images/triceps/Tricep Rope Pushdown.jpg'),
};

export default Exercise_Images;